# Generated by Django 4.2.4 on 2023-08-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='enani', max_length=254),
        ),
    ]
