# Generated by Django 4.2.4 on 2023-08-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
