# Generated by Django 4.2.4 on 2023-08-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_login_email_remove_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
