# Generated by Django 4.2.4 on 2023-08-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_login_email_remove_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
