# Generated by Django 4.2.4 on 2023-08-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='extra',
            new_name='Characteristic',
        ),
    ]
