# Generated by Django 4.2.4 on 2023-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_extra_pizza_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
