# Generated by Django 4.2.4 on 2023-08-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_burger_juice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burger',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='juice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
    ]
