# Generated by Django 4.2.4 on 2023-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_juice_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Characteristic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
