# Generated by Django 4.2.4 on 2023-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_pizza_category_alter_pizza_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.CharField(blank=True, choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Juice', 'Juice')], max_length=50, null=True),
        ),
    ]
