# Generated by Django 4.2.4 on 2023-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_pizza_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='category',
            field=models.CharField(blank=True, choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Juice', 'Juice')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juice',
            name='category',
            field=models.CharField(blank=True, choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Juice', 'Juice')], max_length=50, null=True),
        ),
    ]
