# Generated by Django 4.2.4 on 2023-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_burger_category_juice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='Characteristic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
