# Generated by Django 4.2.4 on 2023-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_juice_datime'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='datime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='datime',
            field=models.DateTimeField(null=True),
        ),
    ]
