# Generated by Django 4.2.4 on 2023-08-11 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_burger_datime_pizza_datime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='datime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='juice',
            name='datime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='datime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
