# Generated by Django 4.2.4 on 2023-08-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
    ]
